### ISSUE TITLE
`yarn dev` gives Package path not imported error

### ISSUE THREAD

**Issue by PriyavKaneria** [jerriclynsjohn/svelte-storybook-tailwind#14]
On setting up the quickstart using Node v14.18.0 and yarn v1.22.15
`yarn dev` gives the following error
```
[!] Error: Package subpath './compiler.js' is not defined by "exports" in .....\my-svelte-project\node_modules\svelte\package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './compiler.js' is not defined by "exports" in ....\my-svelte-project\node_modules\svelte\package.json
    at new NodeError (internal/errors.js:322:7)
    at throwExportsNotFound (internal/modules/esm/resolve.js:322:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:545:3)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (....\my-svelte-project\node_modules\rollup-plugin-svelte\index.js:11:4)  

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "autobuild" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Not sure why. 
`yarn stories` works fine

**Comment by PriyavKaneria** [comment]
Can be solved by updateing the `rollup-plugin-svelte` package to version 6.1.1
Nice and useful package btw!
