### ISSUE TITLE
yarn storybook fails

### ISSUE THREAD

**Issue by orefalo** [jerriclynsjohn/svelte-storybook-tailwind#18]
out of the box , followed instructions.
   storybook is a pain to get working.

```
yarn storybook
yarn run v1.22.17
$ start-storybook -p 6006
info @storybook/svelte v6.4.16
info 
info => Loading presets
info => Using implicit CSS loaders
info => Using custom postcss.config.js
info => Using default Webpack4 setup
(node:14571) DeprecationWarning: Relying on the implicit PostCSS loader is deprecated and will be removed in Storybook 7.0.
If you need PostCSS, include '@storybook/addon-postcss' in your '.storybook/main.js' file.

See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-implicit-postcss-loader for details.
(Use `node --trace-deprecation ...` to show where the warning was created)
11% building 16/30 modules 14 active /Users/orefalo/GitRepositories/svelte-related/daisyui/my-svelte-project/node_modules/@storybook/addon-docs/dist/esm/frameworks/svelte/config.js
info => Ignoring cached manager due to change in manager config
12% building 24/30 modules 6 active /Users/orefalo/GitRepositories/svelte-related/daisyui/my-svelte-project/node_modules/@storybook/addon-docs/dist/esm/frameworks/svelte/config.jsℹ ｢wdm｣: wait until bundle finished: 
webpack built preview 1f59b43b36240c7c97be in 9366ms
✖ ｢wdm｣: Hash: 1f59b43b36240c7c97be
Version: webpack 4.46.0
Time: 9366ms
Built at: 01/29/2022 5:11:05 PM
                                            Asset       Size        Chunks                          Chunk Names
                               0.iframe.bundle.js    875 KiB             0  [emitted]        [big]  
                           0.iframe.bundle.js.map      1 MiB             0  [emitted] [dev]         
                               1.iframe.bundle.js    226 KiB             1  [emitted]               
                           1.iframe.bundle.js.map    215 KiB             1  [emitted] [dev]         
                               2.iframe.bundle.js    206 KiB             2  [emitted]               
                           2.iframe.bundle.js.map    145 KiB             2  [emitted] [dev]         
                               3.iframe.bundle.js   9.15 KiB             3  [emitted]               
                           3.iframe.bundle.js.map   6.47 KiB             3  [emitted] [dev]         
                               4.iframe.bundle.js   1.91 MiB             4  [emitted]        [big]  
                           4.iframe.bundle.js.map   2.14 MiB             4  [emitted] [dev]         
                               5.iframe.bundle.js    102 KiB             5  [emitted]               
                           5.iframe.bundle.js.map   87.2 KiB             5  [emitted] [dev]         
                               6.iframe.bundle.js    2.2 KiB             6  [emitted]               
                           6.iframe.bundle.js.map  759 bytes             6  [emitted] [dev]         
                               7.iframe.bundle.js    372 KiB             7  [emitted]        [big]  
                           7.iframe.bundle.js.map    412 KiB             7  [emitted] [dev]         
                               8.iframe.bundle.js   15.7 KiB             8  [emitted]               
                           8.iframe.bundle.js.map   16.6 KiB             8  [emitted] [dev]         
                                      iframe.html   11.6 KiB                [emitted]               
                            main.iframe.bundle.js    103 KiB          main  [emitted]               main
                        main.iframe.bundle.js.map   59.2 KiB          main  [emitted] [dev]         main
                    runtime~main.iframe.bundle.js   36.3 KiB  runtime~main  [emitted]               runtime~main
                runtime~main.iframe.bundle.js.map   37.6 KiB  runtime~main  [emitted] [dev]         runtime~main
static/media/src/stories/assets/code-brackets.svg   1.42 KiB                [emitted]               
       static/media/src/stories/assets/colors.svg   8.31 KiB                [emitted]               
     static/media/src/stories/assets/comments.svg   1.49 KiB                [emitted]               
    static/media/src/stories/assets/direction.svg   1.25 KiB                [emitted]               
         static/media/src/stories/assets/flow.svg   1.36 KiB                [emitted]               
       static/media/src/stories/assets/plugin.svg   2.12 KiB                [emitted]               
         static/media/src/stories/assets/repo.svg    1.6 KiB                [emitted]               
     static/media/src/stories/assets/stackalt.svg   2.49 KiB                [emitted]               
                    vendors~main.iframe.bundle.js   3.99 MiB  vendors~main  [emitted]        [big]  vendors~main
                vendors~main.iframe.bundle.js.map   3.18 MiB  vendors~main  [emitted] [dev]         vendors~main
Entrypoint main [big] = runtime~main.iframe.bundle.js runtime~main.iframe.bundle.js.map vendors~main.iframe.bundle.js vendors~main.iframe.bundle.js.map main.iframe.bundle.js main.iframe.bundle.js.map
[0] multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-config-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/svelte/config.js-generated-config-entry.js ./node_modules/@storybook/svelte/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-config-entry.js ./node_modules/@storybook/addon-measure/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-outline/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-a11y/dist/esm/a11yRunner.js-generated-config-entry.js ./node_modules/@storybook/addon-a11y/dist/esm/a11yHighlight.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js 232 bytes {main} [built]
[./.storybook/preview.js-generated-config-entry.js] 4.39 KiB {main} [built]
[./generated-stories-entry.js] 410 bytes {main} [built]
[./node_modules/@storybook/addon-a11y/dist/esm/a11yHighlight.js-generated-config-entry.js] 3.06 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-a11y/dist/esm/a11yRunner.js-generated-config-entry.js] 3.06 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-config-entry.js] 3.06 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-config-entry.js] 3.07 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-config-entry.js] 3.07 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-config-entry.js] 3.07 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-config-entry.js] 3.07 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-docs/dist/esm/frameworks/svelte/config.js-generated-config-entry.js] 3.07 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-config-entry.js] 3.07 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-measure/dist/esm/preset/addDecorator.js-generated-config-entry.js] 3.07 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-outline/dist/esm/preset/addDecorator.js-generated-config-entry.js] 3.07 KiB {vendors~main} [built]
[./node_modules/@storybook/core-client/dist/esm/globals/globals.js] 105 bytes {vendors~main} [built]
    + 1414 hidden modules

WARNING in ./src/stories/Header.svelte
Module Warning (from ./node_modules/svelte-loader/index.js):
Unused CSS selector "button + button" (72:4)
70:     }
71: 
72:     button + button {
        ^
73:         margin-left: 10px;
74:     }
 @ ./src/stories/Header.stories.svelte 21:0-37 33:14-20 92:15-21
 @ ./src sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(js|jsx|ts|tsx|svelte))$
 @ ./generated-stories-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-config-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/svelte/config.js-generated-config-entry.js ./node_modules/@storybook/svelte/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-config-entry.js ./node_modules/@storybook/addon-measure/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-outline/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-a11y/dist/esm/a11yRunner.js-generated-config-entry.js ./node_modules/@storybook/addon-a11y/dist/esm/a11yHighlight.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js

ERROR in ./src/stories/page.css (./node_modules/css-loader/dist/cjs.js??ref--14-1!./node_modules/@storybook/builder-webpack4/node_modules/postcss-loader/dist/cjs.js??ref--14-2!./src/stories/page.css)
Module build failed (from ./node_modules/@storybook/builder-webpack4/node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS plugin tailwindcss requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/Users/orefalo/GitRepositories/svelte-related/daisyui/my-svelte-project/node_modules/@storybook/builder-webpack4/node_modules/postcss/lib/processor.js:153:15)
    at new Processor (/Users/orefalo/GitRepositories/svelte-related/daisyui/my-svelte-project/node_modules/@storybook/builder-webpack4/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/Users/orefalo/GitRepositories/svelte-related/daisyui/my-svelte-project/node_modules/@storybook/builder-webpack4/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/Users/orefalo/GitRepositories/svelte-related/daisyui/my-svelte-project/node_modules/@storybook/builder-webpack4/node_modules/postcss-loader/dist/index.js:95:20)
 @ ./src/stories/page.css 2:26-200 53:4-74:5 56:18-192
 @ ./src/stories/Page.svelte
 @ ./src/stories/Page.stories.svelte
 @ ./src sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(js|jsx|ts|tsx|svelte))$
 @ ./generated-stories-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-config-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/svelte/config.js-generated-config-entry.js ./node_modules/@storybook/svelte/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-config-entry.js ./node_modules/@storybook/addon-measure/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-outline/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-a11y/dist/esm/a11yRunner.js-generated-config-entry.js ./node_modules/@storybook/addon-a11y/dist/esm/a11yHighlight.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  6.31 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core-common/dist/cjs/templates/index.ejs] 2.06 KiB {HtmlWebpackPlugin_0} [built]
ModuleBuildError: Module build failed (from ./node_modules/@storybook/builder-webpack4/node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS plugin tailwindcss requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/Users/orefalo/GitRepositories/svelte-related/daisyui/my-svelte-project/node_modules/@storybook/builder-webpack4/node_modules/postcss/lib/processor.js:153:15)
    at new Processor (/Users/orefalo/GitRepositories/svelte-related/daisyui/my-svelte-project/node_modules/@storybook/builder-webpack4/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/Users/orefalo/GitRepositories/svelte-related/daisyui/my-svelte-project/node_modules/@storybook/builder-webpack4/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/Users/orefalo/GitRepositories/svelte-related/daisyui/my-svelte-project/node_modules/@storybook/builder-webpack4/node_modules/postcss-loader/dist/index.js:95:20)
    at /Users/orefalo/GitRepositories/svelte-related/daisyui/my-svelte-project/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/orefalo/GitRepositories/svelte-related/daisyui/my-svelte-project/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/orefalo/GitRepositories/svelte-related/daisyui/my-svelte-project/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/orefalo/GitRepositories/svelte-related/daisyui/my-svelte-project/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/Users/orefalo/GitRepositories/svelte-related/daisyui/my-svelte-project/node_modules/@storybook/builder-webpack4/node_modules/postcss-loader/dist/index.js:104:7)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by wtachau** [comment]
I am also having this same issue

**Comment by wtachau** [comment]
@orefalo I believe this should fix it: https://github.com/jerriclynsjohn/svelte-storybook-tailwind/pull/19

I believe you'll need to run storybook with `--no-manager-cache` as well, or you'll have some corrupted cache.

**Comment by orefalo** [comment]
It does. Thank you so much!
