### ISSUE TITLE
Storybook does not work

### ISSUE THREAD

**Issue by GiorgosK** [jerriclynsjohn/svelte-storybook-tailwind#22]
This is what I get after following all the steps described in readme

```
$ yarn storybook
yarn run v1.22.5
$ start-storybook -p 6006
info @storybook/svelte v6.5.6
info 
info => Loading presets
info Addon-docs: using MDX1
info => Using implicit CSS loaders
info => Using custom postcss.config.js
info => Using default Webpack4 setup
(node:2994) DeprecationWarning: Relying on the implicit PostCSS loader is deprecated and will be removed in Storybook 7.0.
If you need PostCSS, include '@storybook/addon-postcss' in your '.storybook/main.js' file.

See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-implicit-postcss-loader for details.
(Use `node --trace-deprecation ...` to show where the warning was created)
10% building 1/8 modules 7 active ...dules/@storybook/addon-a11y/preview.js-generated-config-entry.jsnode:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/websites/demo/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/websites/demo/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/websites/demo/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/websites/demo/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/websites/demo/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/websites/demo/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/websites/demo/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at /home/websites/demo/node_modules/loader-runner/lib/LoaderRunner.js:205:4 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.0.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by NicolasRuleev** [comment]
@GiorgosK, that is related to Node version, see: https://github.com/storybookjs/storybook/issues/18019 or https://github.com/storybookjs/storybook/issues/16555

**Comment by jerriclynsjohn** [comment]
Hey Ive update the repo with the latest versions
